### PR TITLE
Transform ranks to comparisons

### PR DESCRIPTION
**Pull request by Pozdniakov**
Added a function to convert a data frame of ranks to comparisons (as expected by `make_TIRT_data()`).

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Thank you and sorry it took me so long. I will merge this PR and then make some more edits to it.

**Comment by paul-buerkner** [comment]
It is only now that I realized we have such functionality already. Did you check out `make_TIRT_data(..., format = "ranks")`?

**Comment by paul-buerkner** [comment]
Here is an example with the existing functionality:

```R
ranks <- data.frame(
    i1 = c(1,2), i2 = c(2,3), i3 = c(3,1),
    i4 = c(3,1), i5 = c(1,3), i6 = c(2,2)
  )

  # define the blocks of items
  blocks <-
    set_block(c("i1", "i2", "i3"), traits = c("t1", "t2", "t3"),
              signs = c(1, 1, 1)) +
    set_block(c("i4", "i5", "i6"), traits = c("t1", "t2", "t3"),
              signs = c(1, 1, 1))

  # generate the data to be understood by 'thurstonianIRT'
  triplets_long <- make_TIRT_data(
    data = ranks, blocks = blocks, direction = "larger",
    format = "ranks", family = "bernoulli", range = c(0, 1)
  )
```

Are the functions added in this PR supposed to fullfill another purpose?

**Comment by Pozdniakov** [comment]
Hm, interesting, I didn't notice it. Maybe because I started to work with thurstonianIRT before this functionality was added. Sorry!

**Comment by paul-buerkner** [comment]
No worries. I overlooked it myself when merging the PR.

**Pull request merged**
